# Generated by Django 4.2.4 on 2023-08-24 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='event_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
