# Generated by Django 4.2.4 on 2023-08-23 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symptoms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='symptoms',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='symptoms',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
