# Generated by Django 4.2.4 on 2023-08-23 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symptoms', '0002_symptoms_date_alter_symptoms_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='symptoms',
            name='body_part',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
