# Generated by Django 4.2.4 on 2023-08-26 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symptoms', '0004_alter_symptoms_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='symptoms',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
