# Generated by Django 4.2.4 on 2023-08-26 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symptoms', '0005_symptoms_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='symptoms',
            name='factor_other',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='symptoms',
            name='triger_other',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
