# Generated by Django 4.2.4 on 2023-08-26 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symptoms', '0006_symptoms_factor_other_symptoms_triger_other'),
    ]

    operations = [
        migrations.AddField(
            model_name='symptoms',
            name='event_id',
            field=models.TextField(max_length=255, null=True),
        ),
    ]
