# Generated by Django 4.2.4 on 2023-08-31 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0003_event_appointment_events'),
        ('symptoms', '0007_symptoms_event_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='symptoms',
            name='events',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_symptoms', to='calendars.event'),
        ),
    ]
