# Generated by Django 4.2.4 on 2023-08-24 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_city_remove_user_cnic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='access_token',
            field=models.TextField(null=True),
        ),
    ]
