# Generated by Django 4.2.4 on 2023-08-26 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_user_access_token_remove_user_fcm_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='medical_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
