# Generated by Django 4.2.4 on 2023-08-26 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_medical_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='google_id',
            field=models.TextField(null=True),
        ),
    ]
