# Generated by Django 4.2.4 on 2023-08-23 19:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('medicine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='forgot_remainder',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='medicine',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='medicine',
            name='remainder_time',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='medicine',
            name='start_from',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_medicine', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='medicine',
            table='Medicine',
        ),
        migrations.CreateModel(
            name='DosageTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.BigIntegerField(blank=True, db_column='CreatedBy', default=0, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, db_column='CreatedOn')),
                ('modified_by', models.BigIntegerField(blank=True, db_column='ModifiedBy', default=0, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, db_column='ModifiedOn')),
                ('time', models.TimeField(null=True)),
                ('is_active', models.BooleanField(default=True, null=True)),
                ('medicine', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medicine_dosage', to='medicine.medicine')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DosageHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.BigIntegerField(blank=True, db_column='CreatedBy', default=0, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, db_column='CreatedOn')),
                ('modified_by', models.BigIntegerField(blank=True, db_column='ModifiedBy', default=0, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, db_column='ModifiedOn')),
                ('dosage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dosage_history', to='medicine.dosagetime')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
