# Generated by Django 4.2.4 on 2023-08-23 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0002_medicine_forgot_remainder_medicine_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dosagehistory',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='dosagetime',
            name='time',
            field=models.TimeField(null=True, unique=True),
        ),
    ]
