# Generated by Django 4.2.4 on 2023-08-23 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0003_dosagehistory_date_alter_dosagetime_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dosagetime',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
