# Generated by Django 4.2.4 on 2023-08-26 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0004_alter_dosagetime_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='additional_notes',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='dosage_amount',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='end_to',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='frequency',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='medicine',
            name='instructions',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='meal',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='reminders',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='type',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='unit',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
