# Generated by Django 4.2.4 on 2023-08-26 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0006_dosagetime_event_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dosagetime',
            name='event_id',
            field=models.TextField(null=True),
        ),
    ]
