# Generated by Django 4.2.4 on 2023-08-27 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0007_alter_dosagetime_event_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='medication_type_other',
            field=models.TextField(null=True),
        ),
    ]
