# Generated by Django 4.2.4 on 2023-08-27 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0008_medicine_medication_type_other'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(db_column='File', default=None, null=True, upload_to='')),
            ],
            options={
                'db_table': 'Wiztap_Images',
            },
        ),
    ]
