# Generated by Django 4.2.4 on 2023-09-02 19:07

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0012_medicine_custom_frequency'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='days',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10, null=True), null=True, size=7),
        ),
    ]
