# Generated by Django 4.2.4 on 2023-09-03 18:18

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0013_medicine_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='days',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20, null=True), null=True, size=7),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='frequency',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='meal',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='reminders',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='unit',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
